---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      pod: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        pod: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:{{ .Values.appVersion }}
        args:
        - --source=service
        - --source=ingress
        {{- range .Values.domain_filter }}
        - --domain-filter={{ . }}
        {{- end }}
        {{- range .Values.zone_id_filter }}
        - --zone-id-filter={{ . }}
        {{- end }}
        - --provider=aws
        - --policy={{ .Values.update_policy }}
        - --aws-zone-type={{ .Values.aws_zone_type }}
        - --registry=txt
        - --txt-owner-id={{ .Values.txt_owner_id }}
        - --log-level={{ .Values.log_level }}
        - --log-format={{ .Values.log_format }}
        - --interval={{ .Values.interval }}
        {{- if .Values.txt_prefix }}
        - --txt-prefix={{ .Values.txt_prefix }}
        {{- end }}
        {{- if .Values.txt_suffix }}
        - --txt-suffix={{ .Values.txt_suffix }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
      securityContext:
        fsGroup: 65534
