---
appVersion: "v1.1.2"
env: prod

nodePort: 30080
externalLoadbalancer: rmc-digital-prod-main-1482794507.us-east-1.elb.amazonaws.com

disruptionBudget: true

updateStatusOnShutdown: false

requests:
  cpu: 0.03
  memory: 96Mi
limits:
  cpu: 2
  memory: 512Mi
