---
appVersion: "v1.1.2"
env: uat

nodePort: 30080
externalLoadbalancer: rmc-digital-uat-main-578291983.us-east-1.elb.amazonaws.com

disruptionBudget: true

updateStatusOnShutdown: false

requests:
  cpu: 0.03
  memory: 96Mi
limits:
  cpu: 2
  memory: 512Mi
