---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      pod: fluentd
  template:
    metadata:
      labels:
        pod: fluentd
      annotations:
        configHash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:{{ .Values.appVersion }}-debian-cloudwatch-1
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: REGION
              value: {{ .Values.awsRegion }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: RETENTION_IN_DAYS
              value: {{ .Values.logRetentionDays | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: varlibfluentd
              mountPath: /var/lib/fluentd
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.requests.memory }}
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: varlibfluentd
          hostPath:
             path: /var/lib/fluentd
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
             path: /var/lib/docker/containers